<?php

if ($_SERVER['REQUEST_URI'] == '/metrics') {
  header('Content-Type: text/plain; version=0.0.4');

  $metric_name = 'php_app_random_value';
  $value = mt_rand(0, 100) / 10;
  $timestamp = (int)(microtime(true) * 1000);

  echo "# HELP {$metric_name} A random test metric generated by PHP.\n";
  echo "# TYPE {$metric_name} gauge\n";

  echo "{$metric_name}{label=\"test-label\"} {$value} {$timestamp}\n";
  return;
}

echo "Hello Skpr Developer!";
